/// Memur maaş giriş formunda kullanılan yaygın etiketler (emniyet ağırlıklı ünvan örnekleri).

const List<String> kPolisEmniyetUnvanlari = [
  'Polis Memuru',
  'Komiser Yardımcısı',
  'Komiser',
  'Başkomiser',
  'Emniyet Amiri',
  'İlçe Emniyet Müdürü',
  'İlçe Emniyet Müdür Yardımcısı',
  'İl Emniyet Müdürü',
  'İl Emniyet Müdür Yardımcısı',
  'Koruma ve Güvenlik Amiri',
  'Koruma ve Güvenlik Şefi',
  'Koruma ve Güvenlik Görevlisi',
  'İnfaz ve Koruma Memuru',
  'İnfaz ve Koruma Başmemuru',
  'Çarşı ve Mahalle Bekçisi',
  'Bekçi (YH)',
  'Zabıta Memuru',
  'Zabıta Komiseri',
  'Zabıta Amiri',
  'Zabıta Müdürü',
  'Zabıta Şube Müdürü',
  'Memur',
];

const List<String> kAylar12 = [
  'Ocak',
  'Şubat',
  'Mart',
  'Nisan',
  'Mayıs',
  'Haziran',
  'Temmuz',
  'Ağustos',
  'Eylül',
  'Ekim',
  'Kasım',
  'Aralık',
];
