name: saha_2559
description: Saha 2559 - Polis mevzuat, saha, haklar, teşkilat ve kültür için offline Flutter uygulaması.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/json/law_articles.json
    - assets/json/city_contacts.json
    - assets/json/martyrs.json
    - assets/json/field_cards.json

